name: client
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'elm-client/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build
      run: make client

# vim: set et sw=2 sts=2:
